<?php

namespace App\Repository;
use Doctrine\ORM\EntityRepository;
use App\Entity\Saison;

/**
 * ArcherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArcherRepository extends EntityRepository
{
    public function getArchersFromSaison(Saison $saison){
        return $this->createQueryBuilder('a')
            ->join('a.departs','d')
            ->join('d.concours','c')
            ->andWhere('c.saison = :saison')
            ->setParameter('saison',$saison->getId())
            ->addOrderBy('a.nom','asc')
            ->addOrderBy('a.prenom','asc')
            ->getQuery()
            ->getResult()
            ;
    }
}
