<?php

namespace App\Repository;
use App\Entity\Archer;
use App\Entity\Concours;

/**
 * ConcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcoursRepository extends \Doctrine\ORM\EntityRepository
{
}
