<?php
/**
 * Created by PhpStorm.
 * User: floste
 * Date: 22/06/2018
 * Time: 22:34
 */

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Entity\Saison;

/**
 * ResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ResultatRepository extends EntityRepository
{
    public function getPodiumsIndividuelsForSaison(Saison $saison){
        return $this->createQueryBuilder('r')
            ->join('r.depart','d')
            ->join('d.concours','c')
            ->join('d.archer','a')
            ->andWhere('c.saison = :saison')
            ->andWhere('r.placeDefinitive <= 3 ')
            ->setParameter('saison',$saison->getId())
            ->addOrderBy('c.startDate','asc')
            ->getQuery()
            ->getResult()
            ;
    }
}